subscribers:

  camera_reading:
    topic: /transform/image
    queue_size: 99

actions:

  camera_reading:
    name: /yolo_transform/transformed_check_for_objects

publishers:

  object_detector:
    topic: /yolo_transform/transformed_found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /yolo_transform/transformed_bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /yolo_transform/transformed_detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
