subscribers:

  camera_reading:
    topic: /image_raw
    queue_size: 99

actions:

  camera_reading:
    name: /yolo_original/original_check_for_objects

publishers:

  object_detector:
    topic: /yolo_original/original_found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /yolo_original/original_bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /yolo_original/original_detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
